//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLGUIProject.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Server1;Initial Catalog=DatabaseOnServer1;Persist Security Info=True;" +
            "User ID=tempUser;Password=tempPassword")]
        public string Server1
        {
            get
            {
                return ((string)(this["Server1"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Resources\\SQLGUIProject.xml")]
        public string PathToXML
        {
            get
            {
                return ((string)(this["PathToXML"]));
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color cusTxtColor
        {
            get
            {
                return ((global::System.Drawing.Color)(this["cusTxtColor"]));
            }
            set
            {
                this["cusTxtColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color cusTxtBoxColor
        {
            get
            {
                return ((global::System.Drawing.Color)(this["cusTxtBoxColor"]));
            }
            set
            {
                this["cusTxtBoxColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color cusButtonColor
        {
            get
            {
                return ((global::System.Drawing.Color)(this["cusButtonColor"]));
            }
            set
            {
                this["cusButtonColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color cusGridColor
        {
            get
            {
                return ((global::System.Drawing.Color)(this["cusGridColor"]));
            }
            set
            {
                this["cusGridColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color cusGridTxtColor
        {
            get
            {
                return ((global::System.Drawing.Color)(this["cusGridTxtColor"]));
            }
            set
            {
                this["cusGridTxtColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color cusGridHeaderColor
        {
            get
            {
                return ((global::System.Drawing.Color)(this["cusGridHeaderColor"]));
            }
            set
            {
                this["cusGridHeaderColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color cusActiveTxtBoxColor
        {
            get
            {
                return ((global::System.Drawing.Color)(this["cusActiveTxtBoxColor"]));
            }
            set
            {
                this["cusActiveTxtBoxColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color cusInactiveTxtBoxColor
        {
            get
            {
                return ((global::System.Drawing.Color)(this["cusInactiveTxtBoxColor"]));
            }
            set
            {
                this["cusInactiveTxtBoxColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color cusBackColor
        {
            get
            {
                return ((global::System.Drawing.Color)(this["cusBackColor"]));
            }
            set
            {
                this["cusBackColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool customThemeSet
        {
            get
            {
                return ((bool)(this["customThemeSet"]));
            }
            set
            {
                this["customThemeSet"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color cusGroupBoxColor
        {
            get
            {
                return ((global::System.Drawing.Color)(this["cusGroupBoxColor"]));
            }
            set
            {
                this["cusGroupBoxColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color cusSecGridColor
        {
            get
            {
                return ((global::System.Drawing.Color)(this["cusSecGridColor"]));
            }
            set
            {
                this["cusSecGridColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color cusSecGridTxtColor
        {
            get
            {
                return ((global::System.Drawing.Color)(this["cusSecGridTxtColor"]));
            }
            set
            {
                this["cusSecGridTxtColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color cusGridSelectColor
        {
            get
            {
                return ((global::System.Drawing.Color)(this["cusGridSelectColor"]));
            }
            set
            {
                this["cusGridSelectColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color cusGridSelectTxtColor
        {
            get
            {
                return ((global::System.Drawing.Color)(this["cusGridSelectTxtColor"]));
            }
            set
            {
                this["cusGridSelectTxtColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color cusSecGridSelectColor
        {
            get
            {
                return ((global::System.Drawing.Color)(this["cusSecGridSelectColor"]));
            }
            set
            {
                this["cusSecGridSelectColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color cusSecGridSelectTxtColor
        {
            get
            {
                return ((global::System.Drawing.Color)(this["cusSecGridSelectTxtColor"]));
            }
            set
            {
                this["cusSecGridSelectTxtColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color cusTabColor
        {
            get
            {
                return ((global::System.Drawing.Color)(this["cusTabColor"]));
            }
            set
            {
                this["cusTabColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color cusTabTxtColor
        {
            get
            {
                return ((global::System.Drawing.Color)(this["cusTabTxtColor"]));
            }
            set
            {
                this["cusTabTxtColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color cusPressedTabColor
        {
            get
            {
                return ((global::System.Drawing.Color)(this["cusPressedTabColor"]));
            }
            set
            {
                this["cusPressedTabColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color cusPressedTabTxtColor
        {
            get
            {
                return ((global::System.Drawing.Color)(this["cusPressedTabTxtColor"]));
            }
            set
            {
                this["cusPressedTabTxtColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color cusTabBorderColor
        {
            get
            {
                return ((global::System.Drawing.Color)(this["cusTabBorderColor"]));
            }
            set
            {
                this["cusTabBorderColor"] = value;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Resources\\default.xml")]
        public string PathToDefaultXML
        {
            get
            {
                return ((string)(this["PathToDefaultXML"]));
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cusFont
        {
            get
            {
                return ((string)(this["cusFont"]));
            }
            set
            {
                this["cusFont"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color cusHyperLnkColor
        {
            get
            {
                return ((global::System.Drawing.Color)(this["cusHyperLnkColor"]));
            }
            set
            {
                this["cusHyperLnkColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8.25")]
        public float cusFontSize
        {
            get
            {
                return ((float)(this["cusFontSize"]));
            }
            set
            {
                this["cusFontSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int cusFontInd
        {
            get
            {
                return ((int)(this["cusFontInd"]));
            }
            set
            {
                this["cusFontInd"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Resources\\ChangeLog.txt")]
        public string PathToChangelog
        {
            get
            {
                return ((string)(this["PathToChangelog"]));
            }
            set
            {
                this["PathToChangelog"] = value;
            }
        }
    }
}
